### ISSUE TITLE
Overlapping Layout issue on blog post(s?)

### ISSUE THREAD

**Issue by wingmatt** [wp-graphql/wpgraphql.com#10]
Hi there,

I'm a relative newcomer to WPGraphQL, and have been going through the docs and blog posts to get up to speed.

I noticed at least one blog post seems to have issues with the post content layout: ['Query posts based on Advanced Custom Field values by Registering a Custom “where” Argument'](https://www.wpgraphql.com/2020/04/14/query-posts-based-on-advanced-custom-field-values-by-registering-a-custom-where-argument/). 

I'm using Windows 10, and in both Firefox and Chrome the code blocks all seem to lump together under the "Filter the connection resolver" heading. Poking around in the inspector, it appears they are covering up more explanatory text. Screenshot attached.

This isn't a universal issue. I've found plenty of other posts with regular layouts such as [this one](https://www.wpgraphql.com/2018/11/16/querying-sticky-posts-with-graphql/). I haven't noticed other affected posts yet but will update here if I run into them.

I do have some Gatsby & CSS experience, and would be happy to troubleshoot what might be happening here on the affected post(s) if you'd like!

Small update: I think I found the CSS rule causing this. Disabling the following inline CSS rule on the post restored the layout for me:

```css
.css-15p9n5u {
    height: 24px;
}
```

Not sure what's causing/generating that rule but I hope that helps.

![wpgraphql-post-layout-bug](https://user-images.githubusercontent.com/20592216/101699206-9d306300-3a2f-11eb-945d-6c6937c19f21.png)

**Comment by dhovart** [comment]
Was about to report exactly this.

**Comment by moonmeister** [comment]
I'm not seeing this issue any more, if anyone can reproduce on #37 please re-open this issue.
