### ISSUE TITLE
Typos on "Intro to GraphQL" documentation page

### ISSUE THREAD

**Issue by PieterT2000** [wp-graphql/wpgraphql.com#11]
In the first paragraph after the second heading "What is GraphQL", there is a repeated word. See paraphrase below.

> GraphQL stands for Graph Query Language. Graph, meaning “Application Data Graph”. So, GraphQL is `is` a specification for a Query Language for interacting with API data as a data graph.

In the paragraph under the second code snippet in the "How does GraphQL work?", "viewer" should be replaced by "me".

> Here, the field: “`viewer`” was added to the RootQuery Type and is set to return the type User. The “User” Type is defined to have 2 fields, “id” and “name”.

In the third paragraph under the first code snippet in "Fragments", 'is' should be replace by 'be'?
> Here MenuItem is the type, which should `is` constant. We will cover below on how we can find this type for our query.

**Comment by jasonbahl** [comment]
Thanks @PieterT2000! Got these typos corrected. 🙌
