### ISSUE TITLE
Update gatsby-image to new gatsby-image-plugin

### ISSUE THREAD

**Issue by jacobarriola** [wp-graphql/wpgraphql.com#12]
The new Gatsby Image plugin will offer a simpler API and increased performance, so we should begin updating.

Here's the migration path: https://github.com/liquidweb/www-wp-content/blob/headless-wordpress/mu-plugins/app/src/graphql/Type/Object/raw-content.php#L21

It may also resolve #9

**Comment by jasonbahl** [comment]
Closed by #14
