### ISSUE TITLE
gatsby-plugin-offline serves stale data

### ISSUE THREAD

**Issue by jacobarriola** [wp-graphql/wpgraphql.com#13]
Repro steps:
1. visit /blog
2. publish a new post
3. visit /blog

Expected results:
1. newly published post appears as first entry

Actual results:
1. post doesn't appear unless a user does a hard refresh

Looks like we're running `gatsby-plugin-offline`, which is causing caching issues. This is a known issue: see https://github.com/gatsbyjs/gatsby/issues/11830

**Comment by moonmeister** [comment]
This will be resolved in the next.js version of the site comign with #37
