### ISSUE TITLE
Migrate Community docs to github docs.

### ISSUE THREAD

**Issue by markkelnar** [wp-graphql/wpgraphql.com#20]
Work on pages 
https://www.wpgraphql.com/docs/testing/ https://www.wpgraphql.com/docs/upgrading/ 
https://www.wpgraphql.com/docs/contributing/

**Comment by markkelnar** [comment]
Markdown work being done [here](https://github.com/wp-graphql/wp-graphql/pull/1858/files)

**Comment by bhardie** [comment]
Closed by #19
