### ISSUE TITLE
Headings are being parsed from markdown weird

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wpgraphql.com#22]
There seems to be some funky parsing happening on headings coming from markdown. 

On this page: https://www.wpgraphql.com/docs/graphql-resolvers/#overriding-existing-resolvers

We see the following heading: 

![Screen Shot 2021-05-14 at 9 15 24 AM](https://user-images.githubusercontent.com/1260765/118291511-ebd9a180-b494-11eb-9485-6aadadb338e0.png)

But in the markdown (https://github.com/wp-graphql/wp-graphql/blob/develop/docs/graphql-resolvers.md), the content is: 

```markdown
### graphql_pre_resolve_field filter
```

I would expect this to look something like: 

![Screen Shot 2021-05-14 at 9 19 08 AM](https://user-images.githubusercontent.com/1260765/118292026-71f5e800-b495-11eb-878a-a0879c2fd2c3.png)

----

Quick research shows this markup: 

<img width="645" alt="Screen Shot 2021-05-14 at 9 19 34 AM" src="https://user-images.githubusercontent.com/1260765/118292084-80dc9a80-b495-11eb-8ce8-2d1b067d40c0.png">

Which leads me to believe possibly the parsing logic for `<pre>` tags isn't strict enough and thinks the word `pre` in the heading is a `<pre>` tag? 

🤔 

Could be wrong, but worth noting.

**Comment by markkelnar** [comment]
Findings so far:

The markdown remark query returned from the graphql query is putting emphasis around the 'pre' in the html payload.

  markdownRemark(frontmatter: {uri: {eq: "/docs/graphql-resolvers/"}}) {
    frontmatter {
      title
      uri
    }
    html
  }

`<h3>graphql<em>pre</em>resolve_field filter</h3>`

**Comment by markkelnar** [comment]
It's not the word pre, it's the underscores in the string.

```
### a_b__c_d_e_f_g

test a_b__c_d_e_f_g and `a_b__c_d_e_f_g`
```

queries as

```
<h3>a<em>b__c</em>d<em>e</em>f_g</h3>

<p>test a<em>b__c</em>d<em>e</em>f<em>g and `a</em>b_<em>c</em>d<em>e</em>f_g`</p>
```
