### ISSUE TITLE
docs page right nav bounce

### ISSUE THREAD

**Issue by chwan97** [wp-graphql/wpgraphql.com#24]
docs page right nav bounce 

https://www.wpgraphql.com/docs/intro-to-graphql/

pointer the `the Learning More` section

**Comment by moonmeister** [comment]
Not sure what you mean, if you can show us in a video or more description on how to reproduce this, that'd be great. Please include what browser you're using too.

**Comment by chwan97** [comment]
Here is bug's record, https://youtu.be/ioPqLQHOsDY

every browser can replay it.

**Comment by moonmeister** [comment]
Thanks!! Will look into.

**Comment by moonmeister** [comment]
not an issue in #37
