### ISSUE TITLE
Frameworks logos are disappearing in the homepage

### ISSUE THREAD

**Issue by castroalves** [wp-graphql/wpgraphql.com#9]
Hello,

I've just found small bug by chance in the home page.

To reproduce the issue, do the following steps:

- Open the homepage
- Go to any other page of the website (e.g. Extensions)
- Go back home (click on the logo)
- Mouse over the logos (they should disappear)

It only happens whenever you visit other page starting from the home page and then go back home. If you open other page directly and then go to the home page, it doesn't happen.

JFYI, I'm using:

- Chrome Version 87.0.4280.67 (Official Build) (x86_64)
- macOS Catalina 10.15.7

**Comment by jasonbahl** [comment]
Thanks for reporting!

I'm able to replicate this, also in Chrome. We'll take a look. 👀

**Comment by jacobarriola** [comment]
At first glance, it seems to be centered around gatsby-image setting an `opacity: 0`. This is probably a good opportunity to begin updating to the newest `gatsby-plugin-image` package anyway.

Migration guide: https://www.gatsbyjs.com/docs/reference/release-notes/image-migration-guide/

![Screen Shot 2021-03-10 at 8 11 26 AM](https://user-images.githubusercontent.com/1371573/110660928-e9975600-8178-11eb-8f75-69d13cdbca6f.png)

**Comment by jacobarriola** [comment]
@jasonbahl looks like #14 has fixed this. I'm no longer able to reproduce the issue.

**Comment by jasonbahl** [comment]
@jacobarriola I concur. I also cannot reproduce. Thanks!!! 🙌
